import Script from 'next/script'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
       <script async src="https://kit.fontawesome.com/2d9b67a497.js" crossOrigin="anonymous"></script>
       <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
      </head>
      <body>{children}</body>
    </html>
  )
}
